FROM jenkins/jenkins:lts

USER root

# Install required tools
RUN apt-get update && apt-get install -y \
    docker.io \
    docker-compose \
    python3 \
    python3-pip \
    git \
    curl \
    && apt-get clean

# Add Jenkins user to docker group (IMPORTANT)
RUN usermod -aG docker jenkins

USER jenkins