FROM jenkins/jenkins:lts

USER root

RUN apt-get update && apt-get install -y \
    docker.io \
    docker-compose \
    python3 \
    python3-pip \
    python3-venv \
    git \
    curl \
    && apt-get clean

RUN usermod -aG docker jenkins

USER jenkins