services:
  app:
    build: .
    container_name: nids_app
    depends_on:
      - redis
      - cassandra
      - kafka
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CASSANDRA_HOST: cassandra
      CASSANDRA_PORT: 9042
      KAFKA_BOOTSTRAP_SERVERS: "nids_kafka:9092"
    volumes:
      - ./src:/app/src
    networks:
      - nids_net

  redis:
    image: redis:7-alpine
    container_name: nids_redis
    expose:
      - "6379"
    ports:
      - "6379:6379"
    networks:
      - nids_net

  cassandra:
    image: cassandra:4.1
    container_name: nids_cassandra
    expose:
      - "9042"
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_CLUSTER_NAME: nids_cluster
    volumes:
      - cassandra_data:/var/lib/cassandra
    networks:
      - nids_net

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: nids_kafka
    ports:
      - "19092:19092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,EXTERNAL://0.0.0.0:19092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://nids_kafka:9092,EXTERNAL://localhost:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@nids_kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    networks:
      - nids_net

networks:
  nids_net:
    driver: bridge

volumes:
  cassandra_data:
